#!/bin/sh

syndaemon -i 1 &
exec setxkbmap -option ctrl:nocaps &
exec xscreensaver &
exec xset r rate 250 100 &

# need this for #define to work, apparently
exec xrdb -load ~/.Xdefaults &

if test -f ~/.local/X/xinitrc; then
	. ~/.local/X/xinitrc
fi
